---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: argocd-storage 
  resources:
    requests:
      storage: 500Mi
